'use client';

import React, { useState } from 'react';
import { Card, CardHeader, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { 
  Brain, Sparkles, FileText, BookOpen, Clock, 
  Download, Share, Copy, RefreshCw, Lightbulb,
  Target, Users, Calendar, ChevronRight
} from 'lucide-react';

const aiUsageHistory = [
  {
    id: 1,
    type: "assignment",
    title: "Quadratic Equations - Practice Problems",
    subject: "Mathematics",
    class: "10th B",
    createdAt: "2 hours ago",
    questionsGenerated: 15,
    difficulty: "Medium"
  },
  {
    id: 2,
    type: "lesson",
    title: "Introduction to Acids and Bases",
    subject: "Chemistry",
    class: "9th A",
    createdAt: "1 day ago",
    duration: "45 minutes",
    activities: 4
  },
  {
    id: 3,
    type: "assignment",
    title: "English Grammar - Tenses",
    subject: "English",
    class: "8th C",
    createdAt: "3 days ago",
    questionsGenerated: 20,
    difficulty: "Easy"
  },
  {
    id: 4,
    type: "lesson",
    title: "Photosynthesis Process",
    subject: "Biology",
    class: "10th A",
    createdAt: "1 week ago",
    duration: "60 minutes",
    activities: 5
  },
  {
    id: 5,
    type: "assignment",
    title: "Indian History - Independence Movement",
    subject: "Social Science",
    class: "9th B",
    createdAt: "1 week ago",
    questionsGenerated: 12,
    difficulty: "Hard"
  }
];

const AssignmentGenerator: React.FC = () => {
  const [formData, setFormData] = useState({
    subject: '',
    class: '',
    chapter: '',
    questionType: '',
    difficulty: '',
    numQuestions: '10',
    duration: '60',
    instructions: ''
  });
  
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedContent, setGeneratedContent] = useState('');

  const handleGenerate = async () => {
    setIsGenerating(true);
    // Simulate AI generation
    setTimeout(() => {
      setGeneratedContent(`
# ${formData.subject} Assignment - ${formData.chapter}

**Class:** ${formData.class} | **Duration:** ${formData.duration} minutes | **Difficulty:** ${formData.difficulty}

## Instructions
Answer all questions. Show your working clearly.

## Questions

1. **Multiple Choice Questions**
   - Solve for x: 2x² + 5x - 3 = 0
     a) x = 1, -3/2  b) x = -1, 3/2  c) x = 2, -1  d) x = -2, 1

2. **Short Answer Questions**
   - Explain the quadratic formula and when it is most useful.
   - Find the discriminant of x² - 4x + 4 = 0 and interpret its meaning.

3. **Long Answer Questions**
   - A ball is thrown upward with initial velocity 20 m/s. The height equation is h = 20t - 5t². 
     Find when the ball reaches maximum height and calculate that height.

## Marking Scheme
- Multiple Choice: 2 marks each
- Short Answer: 5 marks each  
- Long Answer: 10 marks each
- Total: 30 marks

---
*Generated by AI Assistant - UK-GSMP Platform*
      `);
      setIsGenerating(false);
    }, 3000);
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Generation Form */}
        <Card>
          <CardHeader>
            <h3 className="text-lg font-semibold flex items-center">
              <Sparkles className="h-5 w-5 mr-2 text-orange-500" />
              Generate Assignment
            </h3>
            <p className="text-sm text-gray-600">
              Create customized assignments aligned with NCERT curriculum
            </p>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Select value={formData.subject} onValueChange={(value) => setFormData({...formData, subject: value})}>
                <SelectTrigger>
                  <SelectValue placeholder="Select Subject" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="mathematics">Mathematics</SelectItem>
                  <SelectItem value="science">Science</SelectItem>
                  <SelectItem value="english">English</SelectItem>
                  <SelectItem value="social-science">Social Science</SelectItem>
                  <SelectItem value="hindi">Hindi</SelectItem>
                </SelectContent>
              </Select>

              <Select value={formData.class} onValueChange={(value) => setFormData({...formData, class: value})}>
                <SelectTrigger>
                  <SelectValue placeholder="Select Class" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="6th">Class 6</SelectItem>
                  <SelectItem value="7th">Class 7</SelectItem>
                  <SelectItem value="8th">Class 8</SelectItem>
                  <SelectItem value="9th">Class 9</SelectItem>
                  <SelectItem value="10th">Class 10</SelectItem>
                  <SelectItem value="11th">Class 11</SelectItem>
                  <SelectItem value="12th">Class 12</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <Input
              placeholder="Chapter/Topic (e.g., Quadratic Equations)"
              value={formData.chapter}
              onChange={(e) => setFormData({...formData, chapter: e.target.value})}
            />

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Select value={formData.questionType} onValueChange={(value) => setFormData({...formData, questionType: value})}>
                <SelectTrigger>
                  <SelectValue placeholder="Question Type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="mixed">Mixed (MCQ + Short + Long)</SelectItem>
                  <SelectItem value="mcq">Multiple Choice Only</SelectItem>
                  <SelectItem value="short">Short Answer Only</SelectItem>
                  <SelectItem value="long">Long Answer Only</SelectItem>
                  <SelectItem value="practical">Practical/Application</SelectItem>
                </SelectContent>
              </Select>

              <Select value={formData.difficulty} onValueChange={(value) => setFormData({...formData, difficulty: value})}>
                <SelectTrigger>
                  <SelectValue placeholder="Difficulty Level" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="easy">Easy</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="hard">Hard</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Input
                type="number"
                placeholder="Number of Questions"
                value={formData.numQuestions}
                onChange={(e) => setFormData({...formData, numQuestions: e.target.value})}
              />
              <Input
                type="number"
                placeholder="Duration (minutes)"
                value={formData.duration}
                onChange={(e) => setFormData({...formData, duration: e.target.value})}
              />
            </div>

            <Textarea
              placeholder="Special instructions or focus areas (optional)"
              value={formData.instructions}
              onChange={(e) => setFormData({...formData, instructions: e.target.value})}
              rows={3}
            />

            <Button 
              onClick={handleGenerate} 
              disabled={isGenerating || !formData.subject || !formData.class || !formData.chapter}
              className="w-full"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                  Generating Assignment...
                </>
              ) : (
                <>
                  <Brain className="h-4 w-4 mr-2" />
                  Generate Assignment
                </>
              )}
            </Button>
          </CardContent>
        </Card>

        {/* Generated Content Preview */}
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold flex items-center">
                <FileText className="h-5 w-5 mr-2 text-blue-500" />
                Generated Preview
              </h3>
              {generatedContent && (
                <div className="flex space-x-2">
                  <Button size="sm" variant="outline">
                    <Copy className="h-4 w-4 mr-1" />
                    Copy
                  </Button>
                  <Button size="sm" variant="outline">
                    <Download className="h-4 w-4 mr-1" />
                    Export
                  </Button>
                  <Button size="sm" variant="outline">
                    <Share className="h-4 w-4 mr-1" />
                    Share
                  </Button>
                </div>
              )}
            </div>
          </CardHeader>
          <CardContent>
            {generatedContent ? (
              <div className="bg-gray-50 rounded-lg p-4 max-h-96 overflow-y-auto">
                <pre className="whitespace-pre-wrap text-sm font-mono">
                  {generatedContent}
                </pre>
              </div>
            ) : (
              <div className="text-center py-12 text-gray-500">
                <Brain className="h-12 w-12 mx-auto mb-4 text-gray-300" />
                <p>Generated assignment will appear here</p>
                <p className="text-sm mt-1">Fill in the form and click generate to start</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

const LessonPlanner: React.FC = () => {
  const [lessonData, setLessonData] = useState({
    subject: '',
    class: '',
    topic: '',
    duration: '45',
    objectives: '',
    priorKnowledge: ''
  });

  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedLesson, setGeneratedLesson] = useState('');

  const handleGenerateLesson = async () => {
    setIsGenerating(true);
    setTimeout(() => {
      setGeneratedLesson(`
# Lesson Plan: ${lessonData.topic}

**Subject:** ${lessonData.subject} | **Class:** ${lessonData.class} | **Duration:** ${lessonData.duration} minutes

## Learning Objectives
By the end of this lesson, students will be able to:
- Understand the concept of acids and bases
- Identify common acids and bases in daily life
- Explain the properties of acids and bases
- Use indicators to test for acids and bases

## Prior Knowledge Required
- Basic understanding of chemical substances
- Familiarity with pH concept

## Lesson Structure

### Introduction (10 minutes)
- **Hook Activity:** Show lemon, baking soda, soap - ask students what they have in common
- **Question:** "What makes lemon sour and soap slippery?"
- **Objective Sharing:** Today we'll discover acids and bases around us

### Main Content (25 minutes)

#### Part 1: What are Acids? (12 minutes)
- **Definition:** Substances that taste sour and turn blue litmus red
- **Examples:** Lemon (citric acid), vinegar (acetic acid), gastric juice (HCl)
- **Properties:** Sour taste, react with metals, conduct electricity
- **Demo:** Test lemon juice with litmus paper

#### Part 2: What are Bases? (13 minutes)
- **Definition:** Substances that taste bitter, feel slippery, turn red litmus blue
- **Examples:** Soap, baking soda, antacids
- **Properties:** Bitter taste, slippery feel, conduct electricity
- **Demo:** Test soap solution with litmus paper

### Activity (8 minutes)
**"Acid-Base Detective"**
- Students identify household items as acid/base/neutral
- Use red and blue litmus paper strips
- Record observations in table

### Conclusion (2 minutes)
- Quick recap: Acids vs Bases properties
- Tomorrow: We'll learn about neutralization

## Assessment
- **Formative:** Questioning during lesson, observation during activity
- **Homework:** Find 5 acids and 5 bases at home, test with parents' help

## Resources Needed
- Litmus paper strips (red & blue)
- Lemon, soap solution, baking soda solution
- Household items for testing
- Chart paper for observations

## Differentiation Strategies
- **Advanced learners:** Research pH scale
- **Struggling learners:** Focus on examples and hands-on testing
- **Visual learners:** Use color charts and demonstrations

---
*Generated by AI Lesson Planner - UK-GSMP Platform*
      `);
      setIsGenerating(false);
    }, 3000);
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Lesson Planning Form */}
        <Card>
          <CardHeader>
            <h3 className="text-lg font-semibold flex items-center">
              <BookOpen className="h-5 w-5 mr-2 text-green-500" />
              Create Lesson Plan
            </h3>
            <p className="text-sm text-gray-600">
              Generate detailed lesson plans aligned with pedagogical best practices
            </p>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Select value={lessonData.subject} onValueChange={(value) => setLessonData({...lessonData, subject: value})}>
                <SelectTrigger>
                  <SelectValue placeholder="Select Subject" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Mathematics">Mathematics</SelectItem>
                  <SelectItem value="Science">Science</SelectItem>
                  <SelectItem value="English">English</SelectItem>
                  <SelectItem value="Social Science">Social Science</SelectItem>
                  <SelectItem value="Hindi">Hindi</SelectItem>
                </SelectContent>
              </Select>

              <Select value={lessonData.class} onValueChange={(value) => setLessonData({...lessonData, class: value})}>
                <SelectTrigger>
                  <SelectValue placeholder="Select Class" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="6th">Class 6</SelectItem>
                  <SelectItem value="7th">Class 7</SelectItem>
                  <SelectItem value="8th">Class 8</SelectItem>
                  <SelectItem value="9th">Class 9</SelectItem>
                  <SelectItem value="10th">Class 10</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <Input
              placeholder="Lesson Topic (e.g., Introduction to Acids and Bases)"
              value={lessonData.topic}
              onChange={(e) => setLessonData({...lessonData, topic: e.target.value})}
            />

            <Select value={lessonData.duration} onValueChange={(value) => setLessonData({...lessonData, duration: value})}>
              <SelectTrigger>
                <SelectValue placeholder="Lesson Duration" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="30">30 minutes</SelectItem>
                <SelectItem value="45">45 minutes</SelectItem>
                <SelectItem value="60">60 minutes</SelectItem>
                <SelectItem value="90">90 minutes</SelectItem>
              </SelectContent>
            </Select>

            <Textarea
              placeholder="Learning objectives (what students should achieve)"
              value={lessonData.objectives}
              onChange={(e) => setLessonData({...lessonData, objectives: e.target.value})}
              rows={3}
            />

            <Textarea
              placeholder="Prior knowledge required (what students should already know)"
              value={lessonData.priorKnowledge}
              onChange={(e) => setLessonData({...lessonData, priorKnowledge: e.target.value})}
              rows={2}
            />

            <Button 
              onClick={handleGenerateLesson} 
              disabled={isGenerating || !lessonData.subject || !lessonData.class || !lessonData.topic}
              className="w-full"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                  Creating Lesson Plan...
                </>
              ) : (
                <>
                  <Lightbulb className="h-4 w-4 mr-2" />
                  Generate Lesson Plan
                </>
              )}
            </Button>
          </CardContent>
        </Card>

        {/* Generated Lesson Plan */}
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold flex items-center">
                <Target className="h-5 w-5 mr-2 text-purple-500" />
                Generated Lesson Plan
              </h3>
              {generatedLesson && (
                <div className="flex space-x-2">
                  <Button size="sm" variant="outline">
                    <Copy className="h-4 w-4 mr-1" />
                    Copy
                  </Button>
                  <Button size="sm" variant="outline">
                    <Download className="h-4 w-4 mr-1" />
                    Export PDF
                  </Button>
                </div>
              )}
            </div>
          </CardHeader>
          <CardContent>
            {generatedLesson ? (
              <div className="bg-gray-50 rounded-lg p-4 max-h-96 overflow-y-auto">
                <pre className="whitespace-pre-wrap text-sm font-mono">
                  {generatedLesson}
                </pre>
              </div>
            ) : (
              <div className="text-center py-12 text-gray-500">
                <BookOpen className="h-12 w-12 mx-auto mb-4 text-gray-300" />
                <p>Generated lesson plan will appear here</p>
                <p className="text-sm mt-1">Fill in the details and generate your plan</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default function AIAssistantPage() {
  return (
    <div className="max-w-7xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 flex items-center">
            <Brain className="h-8 w-8 mr-3 text-orange-500" />
            AI Assistant Center
          </h1>
          <p className="text-gray-600 mt-2">
            Leverage AI to create assignments, lesson plans, and educational content
          </p>
        </div>
        <div className="flex items-center space-x-4">
          <Badge variant="secondary" className="bg-orange-100 text-orange-700">
            15 generations this month
          </Badge>
          <Badge variant="secondary" className="bg-green-100 text-green-700">
            12 hours saved
          </Badge>
        </div>
      </div>

      {/* Usage Statistics */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-orange-600">15</div>
            <div className="text-sm text-gray-600">Assignments Generated</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-green-600">8</div>
            <div className="text-sm text-gray-600">Lesson Plans Created</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-blue-600">12h</div>
            <div className="text-sm text-gray-600">Time Saved</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-purple-600">95%</div>
            <div className="text-sm text-gray-600">Satisfaction Rate</div>
          </CardContent>
        </Card>
      </div>

      {/* Main Content Tabs */}
      <Tabs defaultValue="assignment" className="w-full">
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="assignment">Assignment Generator</TabsTrigger>
          <TabsTrigger value="lesson">Lesson Planner</TabsTrigger>
          <TabsTrigger value="history">Generation History</TabsTrigger>
        </TabsList>

        <TabsContent value="assignment" className="space-y-6">
          <AssignmentGenerator />
        </TabsContent>

        <TabsContent value="lesson" className="space-y-6">
          <LessonPlanner />
        </TabsContent>

        <TabsContent value="history" className="space-y-6">
          <Card>
            <CardHeader>
              <h3 className="text-lg font-semibold flex items-center">
                <Clock className="h-5 w-5 mr-2 text-gray-500" />
                Recent AI Generations
              </h3>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {aiUsageHistory.map((item) => (
                  <div key={item.id} className="flex items-center justify-between p-4 border rounded-lg hover:bg-gray-50 transition-colors">
                    <div className="flex items-center space-x-4">
                      <div className={`p-2 rounded-lg ${
                        item.type === 'assignment' 
                          ? 'bg-orange-100 text-orange-600' 
                          : 'bg-green-100 text-green-600'
                      }`}>
                        {item.type === 'assignment' ? (
                          <FileText className="h-4 w-4" />
                        ) : (
                          <BookOpen className="h-4 w-4" />
                        )}
                      </div>
                      <div>
                        <h4 className="font-semibold text-gray-900">{item.title}</h4>
                        <p className="text-sm text-gray-600">
                          {item.subject} • {item.class} • {item.createdAt}
                        </p>
                        <div className="flex items-center space-x-4 mt-1">
                          {item.questionsGenerated && (
                            <Badge variant="outline" className="text-xs">
                              {item.questionsGenerated} questions
                            </Badge>
                          )}
                          {item.difficulty && (
                            <Badge variant="outline" className="text-xs">
                              {item.difficulty}
                            </Badge>
                          )}
                          {item.duration && (
                            <Badge variant="outline" className="text-xs">
                              {item.duration} min
                            </Badge>
                          )}
                          {item.activities && (
                            <Badge variant="outline" className="text-xs">
                              {item.activities} activities
                            </Badge>
                          )}
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Button size="sm" variant="outline">
                        <Download className="h-4 w-4 mr-1" />
                        Export
                      </Button>
                      <Button size="sm" variant="outline">
                        <ChevronRight className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
