'use client';

import React, { useState } from 'react';
import { Card, CardHeader, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { 
  Wand2, 
  FileText, 
  Copy, 
  Download, 
  Share, 
  RefreshCw, 
  Brain,
  BookOpen,
  Clock,
  Target,
  Users,
  Settings,
  History,
  Sparkles,
  CheckCircle2,
  AlertCircle,
  ChevronRight,
  Lightbulb
} from 'lucide-react';

// Assignment Generator Form Data Interface
interface AssignmentForm {
  subject: string;
  class: string;
  chapter: string;
  questionType: string;
  difficulty: string;
  numQuestions: string;
  duration: string;
  instructions: string;
  focusAreas: string;
}

// Recent Generations Data
const recentGenerations = [
  {
    id: 1,
    title: "Quadratic Equations - Practice Problems",
    subject: "Mathematics",
    class: "10th B",
    createdAt: "2 hours ago",
    questionsGenerated: 15,
    difficulty: "Medium"
  },
  {
    id: 2,
    title: "Chemical Reactions - Assessment",
    subject: "Science",
    class: "9th A",
    createdAt: "1 day ago",
    questionsGenerated: 12,
    difficulty: "Easy"
  },
  {
    id: 3,
    title: "English Grammar - Tenses Practice",
    subject: "English",
    class: "8th C",
    createdAt: "3 days ago",
    questionsGenerated: 20,
    difficulty: "Medium"
  }
];

// Assignment Generator Page Component
export default function AssignmentGeneratorPage() {
  const [formData, setFormData] = useState<AssignmentForm>({
    subject: '',
    class: '',
    chapter: '',
    questionType: '',
    difficulty: '',
    numQuestions: '10',
    duration: '60',
    instructions: '',
    focusAreas: ''
  });
  
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedContent, setGeneratedContent] = useState('');
  const [generationStats] = useState({
    totalGenerated: 15,
    timeSaved: 12,
    averageRating: 4.8
  });

  const handleGenerate = async () => {
    setIsGenerating(true);
    
    // Simulate AI generation process
    setTimeout(() => {
      const generatedAssignment = `
# ${formData.subject} Assignment - ${formData.chapter}

**Class:** ${formData.class} | **Duration:** ${formData.duration} minutes | **Difficulty:** ${formData.difficulty}

## Instructions
- Answer all questions clearly and legibly
- Show all working for mathematical problems
- Read questions carefully before attempting
- Manage your time effectively

---

## Section A: Multiple Choice Questions (2 marks each)

**1.** Which of the following is the correct quadratic formula?
   a) x = (-b ± √(b² - 4ac)) / 2a
   b) x = (-b ± √(b² + 4ac)) / 2a  
   c) x = (b ± √(b² - 4ac)) / 2a
   d) x = (-b ± √(b² - 4ac)) / a

**2.** The discriminant of the equation x² - 6x + 9 = 0 is:
   a) 0
   b) 36
   c) -36
   d) 9

**3.** If the roots of a quadratic equation are real and equal, then the discriminant is:
   a) Greater than zero
   b) Less than zero
   c) Equal to zero
   d) Cannot be determined

---

## Section B: Short Answer Questions (5 marks each)

**4.** Find the roots of the quadratic equation x² - 7x + 12 = 0 using factorization method.

**5.** Determine the nature of roots for the equation 2x² - 3x + 5 = 0 without solving it.

**6.** If one root of the equation x² - px + 12 = 0 is 4, find the value of p and the other root.

---

## Section C: Long Answer Questions (10 marks each)

**7.** A ball is thrown vertically upward from the ground with an initial velocity of 20 m/s. The height h (in meters) at time t (in seconds) is given by h = 20t - 5t².
   a) At what time does the ball reach its maximum height?
   b) What is the maximum height reached by the ball?
   c) When does the ball return to the ground?

**8.** The sum of a number and its reciprocal is 2.5. Find the number using quadratic equations. Also verify your answer.

---

## Answer Key

**Section A:**
1. a) x = (-b ± √(b² - 4ac)) / 2a
2. a) 0
3. c) Equal to zero

**Section B:**
4. x = 3, x = 4 (Factorization: (x-3)(x-4) = 0)
5. Discriminant = 9 - 40 = -31 < 0, so roots are imaginary
6. p = 7, other root = 3

**Section C:**
7. a) t = 2 seconds, b) h = 20 meters, c) t = 4 seconds
8. x = 2 or x = 0.5 (from equation x² - 2.5x + 1 = 0)

---

**Total Marks: 50**
**Suggested Time Distribution:**
- Section A: 15 minutes
- Section B: 25 minutes  
- Section C: 20 minutes

*Generated by UK-GSMP AI Assistant*
*Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}*
      `;
      
      setGeneratedContent(generatedAssignment);
      setIsGenerating(false);
    }, 3000);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedContent);
  };

  const downloadAsDocument = () => {
    const element = document.createElement('a');
    const file = new Blob([generatedContent], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `${formData.subject}_Assignment_${formData.chapter}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="max-w-7xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 flex items-center">
            <Wand2 className="h-8 w-8 mr-3 text-violet-500" />
            Assignment Generator
          </h1>
          <p className="text-gray-600 mt-2">
            Create customized assignments with AI assistance, aligned with NCERT curriculum
          </p>
        </div>
        <div className="flex items-center space-x-4">
          <Badge variant="secondary" className="bg-violet-100 text-violet-700">
            {generationStats.totalGenerated} generated this month
          </Badge>
          <Badge variant="secondary" className="bg-emerald-100 text-emerald-700">
            {generationStats.timeSaved}h saved
          </Badge>
        </div>
      </div>

      {/* Statistics Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card className="border-violet-100 shadow-sm">
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-violet-600">{generationStats.totalGenerated}</div>
            <div className="text-sm text-gray-600">Assignments Generated</div>
          </CardContent>
        </Card>
        <Card className="border-violet-100 shadow-sm">
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-emerald-600">{generationStats.timeSaved}h</div>
            <div className="text-sm text-gray-600">Time Saved</div>
          </CardContent>
        </Card>
        <Card className="border-violet-100 shadow-sm">
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-indigo-600">{generationStats.averageRating}</div>
            <div className="text-sm text-gray-600">Average Rating</div>
          </CardContent>
        </Card>
        <Card className="border-violet-100 shadow-sm">
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-rose-600">95%</div>
            <div className="text-sm text-gray-600">Success Rate</div>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-8">
        {/* Generation Form - Left Side */}
        <div className="lg:col-span-2 space-y-6">
          <Card className="border-violet-100 shadow-sm">
            <CardHeader>
              <h3 className="text-lg font-semibold flex items-center">
                <Settings className="h-5 w-5 mr-2 text-violet-500" />
                Assignment Configuration
              </h3>
              <p className="text-sm text-gray-600">
                Configure your assignment parameters for AI generation
              </p>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Basic Information */}
              <div className="space-y-4">
                <div className="grid grid-cols-1 gap-4">
                  <Select value={formData.subject} onValueChange={(value) => setFormData({...formData, subject: value})}>
                    <SelectTrigger className="border-violet-200 focus:border-violet-400">
                      <SelectValue placeholder="Select Subject" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Mathematics">Mathematics</SelectItem>
                      <SelectItem value="Science">Science</SelectItem>
                      <SelectItem value="English">English</SelectItem>
                      <SelectItem value="Social Science">Social Science</SelectItem>
                      <SelectItem value="Hindi">Hindi</SelectItem>
                    </SelectContent>
                  </Select>

                  <Select value={formData.class} onValueChange={(value) => setFormData({...formData, class: value})}>
                    <SelectTrigger className="border-violet-200 focus:border-violet-400">
                      <SelectValue placeholder="Select Class" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="6th">Class 6</SelectItem>
                      <SelectItem value="7th">Class 7</SelectItem>
                      <SelectItem value="8th">Class 8</SelectItem>
                      <SelectItem value="9th">Class 9</SelectItem>
                      <SelectItem value="10th">Class 10</SelectItem>
                      <SelectItem value="11th">Class 11</SelectItem>
                      <SelectItem value="12th">Class 12</SelectItem>
                    </SelectContent>
                  </Select>

                  <Input
                    placeholder="Chapter/Topic (e.g., Quadratic Equations)"
                    value={formData.chapter}
                    onChange={(e) => setFormData({...formData, chapter: e.target.value})}
                    className="border-violet-200 focus:border-violet-400"
                  />
                </div>

                {/* Assignment Parameters */}
                <div className="grid grid-cols-2 gap-4">
                  <Select value={formData.questionType} onValueChange={(value) => setFormData({...formData, questionType: value})}>
                    <SelectTrigger className="border-violet-200 focus:border-violet-400">
                      <SelectValue placeholder="Question Type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="mixed">Mixed (MCQ + Short + Long)</SelectItem>
                      <SelectItem value="mcq">Multiple Choice Only</SelectItem>
                      <SelectItem value="short">Short Answer Only</SelectItem>
                      <SelectItem value="long">Long Answer Only</SelectItem>
                      <SelectItem value="practical">Practical/Application</SelectItem>
                    </SelectContent>
                  </Select>

                  <Select value={formData.difficulty} onValueChange={(value) => setFormData({...formData, difficulty: value})}>
                    <SelectTrigger className="border-violet-200 focus:border-violet-400">
                      <SelectValue placeholder="Difficulty Level" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Easy">Easy</SelectItem>
                      <SelectItem value="Medium">Medium</SelectItem>
                      <SelectItem value="Hard">Hard</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Number of Questions
                    </label>
                    <Input
                      type="number"
                      placeholder="10"
                      value={formData.numQuestions}
                      onChange={(e) => setFormData({...formData, numQuestions: e.target.value})}
                      className="border-violet-200 focus:border-violet-400"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Duration (minutes)
                    </label>
                    <Input
                      type="number"
                      placeholder="60"
                      value={formData.duration}
                      onChange={(e) => setFormData({...formData, duration: e.target.value})}
                      className="border-violet-200 focus:border-violet-400"
                    />
                  </div>
                </div>

                {/* Advanced Options */}
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Special Instructions (Optional)
                    </label>
                    <Textarea
                      placeholder="Any specific requirements or focus areas..."
                      value={formData.instructions}
                      onChange={(e) => setFormData({...formData, instructions: e.target.value})}
                      rows={3}
                      className="border-violet-200 focus:border-violet-400"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Focus Areas (Optional)
                    </label>
                    <Input
                      placeholder="e.g., Real-world applications, Problem-solving"
                      value={formData.focusAreas}
                      onChange={(e) => setFormData({...formData, focusAreas: e.target.value})}
                      className="border-violet-200 focus:border-violet-400"
                    />
                  </div>
                </div>
              </div>

              {/* Generate Button */}
              <Button 
                onClick={handleGenerate} 
                disabled={isGenerating || !formData.subject || !formData.class || !formData.chapter}
                className="w-full bg-gradient-to-r from-violet-500 to-fuchsia-500 hover:from-violet-600 hover:to-fuchsia-600"
                size="lg"
              >
                {isGenerating ? (
                  <>
                    <RefreshCw className="h-5 w-5 mr-2 animate-spin" />
                    Generating Assignment...
                  </>
                ) : (
                  <>
                    <Wand2 className="h-5 w-5 mr-2" />
                    Generate Assignment
                  </>
                )}
              </Button>
            </CardContent>
          </Card>

          {/* Recent Generations */}
          <Card className="border-violet-100 shadow-sm">
            <CardHeader>
              <h3 className="text-lg font-semibold flex items-center">
                <History className="h-5 w-5 mr-2 text-indigo-500" />
                Recent Generations
              </h3>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {recentGenerations.map((item) => (
                  <div key={item.id} className="flex items-center justify-between p-3 bg-violet-50 rounded-lg border border-violet-100">
                    <div className="flex-1">
                      <h4 className="font-medium text-gray-900 text-sm">{item.title}</h4>
                      <p className="text-xs text-gray-600">
                        {item.subject} • {item.class} • {item.createdAt}
                      </p>
                      <div className="flex items-center space-x-2 mt-1">
                        <Badge variant="outline" className="text-xs border-violet-200 text-violet-700">
                          {item.questionsGenerated} questions
                        </Badge>
                        <Badge variant="outline" className="text-xs border-violet-200 text-violet-700">
                          {item.difficulty}
                        </Badge>
                      </div>
                    </div>
                    <Button size="sm" variant="outline" className="border-violet-200 text-violet-700 hover:bg-violet-100">
                      <ChevronRight className="h-4 w-4" />
                    </Button>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Generated Content - Right Side */}
        <div className="lg:col-span-3">
          <Card className="border-violet-100 shadow-sm h-full">
            <CardHeader>
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-semibold flex items-center">
                  <FileText className="h-5 w-5 mr-2 text-indigo-500" />
                  Generated Assignment
                </h3>
                {generatedContent && (
                  <div className="flex space-x-2">
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={copyToClipboard}
                      className="border-violet-200 text-violet-700 hover:bg-violet-50"
                    >
                      <Copy className="h-4 w-4 mr-1" />
                      Copy
                    </Button>
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={downloadAsDocument}
                      className="border-violet-200 text-violet-700 hover:bg-violet-50"
                    >
                      <Download className="h-4 w-4 mr-1" />
                      Download
                    </Button>
                    <Button 
                      size="sm" 
                      variant="outline"
                      className="border-violet-200 text-violet-700 hover:bg-violet-50"
                    >
                      <Share className="h-4 w-4 mr-1" />
                      Share
                    </Button>
                  </div>
                )}
              </div>
              {generatedContent && (
                <div className="flex items-center space-x-4 text-sm text-gray-600">
                  <div className="flex items-center">
                    <Clock className="h-4 w-4 mr-1" />
                    {formData.duration} minutes
                  </div>
                  <div className="flex items-center">
                    <Target className="h-4 w-4 mr-1" />
                    {formData.numQuestions} questions
                  </div>
                  <div className="flex items-center">
                    <BookOpen className="h-4 w-4 mr-1" />
                    {formData.difficulty} difficulty
                  </div>
                </div>
              )}
            </CardHeader>
            <CardContent>
              {generatedContent ? (
                <div className="bg-violet-50 border border-violet-100 rounded-lg p-4">
                  <div className="max-h-[600px] overflow-y-auto">
                    <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 leading-relaxed">
                      {generatedContent}
                    </pre>
                  </div>
                </div>
              ) : (
                <div className="text-center py-16 text-gray-500">
                  <div className="mb-6">
                    <Sparkles className="h-16 w-16 mx-auto text-violet-300 mb-4" />
                    <Brain className="h-12 w-12 mx-auto text-violet-400" />
                  </div>
                  <h4 className="text-lg font-medium text-gray-700 mb-2">
                    Ready to Generate Your Assignment
                  </h4>
                  <p className="text-sm mb-4">
                    Fill in the configuration form and click "Generate Assignment" to create<br />
                    a customized assignment with our AI assistant.
                  </p>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 max-w-md mx-auto text-xs">
                    <div className="flex items-center justify-center p-3 bg-violet-50 rounded-lg border border-violet-100">
                      <CheckCircle2 className="h-4 w-4 mr-2 text-violet-500" />
                      <span>NCERT Aligned</span>
                    </div>
                    <div className="flex items-center justify-center p-3 bg-violet-50 rounded-lg border border-violet-100">
                      <CheckCircle2 className="h-4 w-4 mr-2 text-violet-500" />
                      <span>Auto Answer Key</span>
                    </div>
                    <div className="flex items-center justify-center p-3 bg-violet-50 rounded-lg border border-violet-100">
                      <CheckCircle2 className="h-4 w-4 mr-2 text-violet-500" />
                      <span>Multi-format</span>
                    </div>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Tips & Features */}
      <Card className="border-violet-100 shadow-sm">
        <CardHeader>
          <h3 className="text-lg font-semibold flex items-center">
            <Lightbulb className="h-5 w-5 mr-2 text-amber-500" />
            Tips for Better Assignment Generation
          </h3>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="text-center">
              <div className="w-12 h-12 bg-violet-100 rounded-full flex items-center justify-center mx-auto mb-3">
                <Target className="h-6 w-6 text-violet-600" />
              </div>
              <h4 className="font-medium text-gray-900 mb-2">Be Specific</h4>
              <p className="text-sm text-gray-600">
                Include specific chapter names and topics for more targeted questions
              </p>
            </div>
            <div className="text-center">
              <div className="w-12 h-12 bg-emerald-100 rounded-full flex items-center justify-center mx-auto mb-3">
                <Users className="h-6 w-6 text-emerald-600" />
              </div>
              <h4 className="font-medium text-gray-900 mb-2">Know Your Students</h4>
              <p className="text-sm text-gray-600">
                Choose difficulty levels that match your students' current abilities
              </p>
            </div>
            <div className="text-center">
              <div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center mx-auto mb-3">
                <Clock className="h-6 w-6 text-indigo-600" />
              </div>
              <h4 className="font-medium text-gray-900 mb-2">Time Management</h4>
              <p className="text-sm text-gray-600">
                Set realistic durations - typically 3-5 minutes per question
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
